config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions
  resources :events

  get "/sign-up" => "users#new", as: :sign_up
  get "/sign-in" => "sessions#new", as: :sign_in
  get "/sign-out" => "sessions#destroy", as: :sign_out

  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authenticated_user.rb
class AuthenticatedUser < SimpleDelegator
  def authenticated?
    true
  end
end

app/models/user.rb
class User < Hanami::Entity
  def authenticated?
    false
  end

  Guest = Naught.build do |config|
    config.mimic User

    def first_name
      "Honored Guest"
    end

    def full_name
      "Honored Guest"
    end

    def authenticated?
      false
    end
  end
end

app/models/validator/strong_password.rb
module Validator
  class StrongPassword < ActiveModel::Validator
    def validate(record)
      return if record.password.length > 11

      record.errors.add(:password, :too_short)
    end
  end
end

app/models/validator/unique_email.rb
module Validator
  class UniqueEmail < ActiveModel::Validator
    def validate(record)
      return unless UserRepository.new.email_exists?(record.email)

      record.errors.add(:email, :duplicate)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticated
end

app/controllers/concerns/authenticated.rb
module Authenticated
  extend ActiveSupport::Concern

  included do
    before_action :authenticate_user!
    helper_method :current_user, :signed_in?
  end

  class_methods do
    def public_permissions(*options)
      skip_before_action :authenticate_user!, *options
    end
  end

  def current_user
    user_repository.from_session(session)
  end

  def signed_in?
    current_user.authenticated?
  end

  def authenticate_user!
    return if signed_in?

    redirect_to sign_in_path
  end

private

  def user_repository
    @user_repository ||= UserRepository.new
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  public_permissions only: %i(index show)

  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  public_permissions only: %i(new create)

  attr_reader :session_create
  helper_method :session_create

  # Sign in form (start)
  def new
    @session_create = Session::Create.new
  end

  # Sign in (complete)
  def create
    @session_create = Session::Create.new(**session_create_params)
    if @session_create.call(session)
      redirect_to root_url
    else
      render :new
    end
  end

  # Sign out
  def destroy
    session.destroy
    redirect_to root_path
  end

private

  def session_create_params
    params
      .require(:session)
      .permit(:email, :password)
      .to_h
      .symbolize_keys
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  public_permissions only: %i(new create)

  attr_reader :user_create
  helper_method :user_create

  # Sign up form (start)
  def new
    @user_create = User::Create.new
  end

  # Sign up (complete)
  def create
    @user_create = User::Create.new(**user_create_params)
    if @user_create.call(session)
      redirect_to root_path
    else
      render :new
    end
  end

  # Profile page (needed?)
  def show; end

private

  def user_create_params
    params
      .require(:user)
      .permit(:email, :password, :password_confirmation, :first_name, :last_name)
      .to_h
      .symbolize_keys
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.slim
h1 Events (coming soon)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Nash.rb</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render(partial: "shared/header") %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to(t("link.home"), root_path, class: "navbar-brand")
  .collapse.navbar-collapse
    ul.navbar-nav
      - if signed_in?
        li.nav-item
          = link_to(t("link.sign_out"), sign_out_path, class: "nav-link")
      - else
        li.nav-item
          = link_to(t("link.sign_in"), sign_in_path, class: "nav-link")
        li.nav-item
          = link_to(t("link.sign_up"), sign_up_path, class: "nav-link")

app/views/users/new.html.slim
h1 = t(".title")
= form_for(user_create) do |f|
  - if user_create.errors
    - user_create.errors.full_messages.each do |error|
      .alert.alert-danger role="alert"
        = error
  .form-group
    = f.label(:first_name)
    = f.text_field(:first_name, class: "form-control", required: true)
    = f.label(:last_name)
    = f.text_field(:last_name, class: "form-control", required: true)
  .form-group
    = f.label(:email)
    = f.text_field(:email, class: "form-control", required: true)
  .form-group
    = f.label(:password)
    = f.password_field(:password, class: "form-control", required: true)
    = f.label(:password_confirmation)
    = f.password_field(:password_confirmation, class: "form-control", required: true)
  = f.submit(t(".submit"), class: "btn btn-primary")